### ISSUE TITLE
Incorrect appstream install location

### ISSUE THREAD

**Issue by danirabbit** [hezral/keystrokes#1]
https://github.com/hezral/keystrokes/blob/2897e2137f27f9ecba3e6ce0d2abbdae2c8706e7/data/meson.build#L22

While trying to review your app, Sideload seems to be stuck on not being able to load appdata. I noticed you're installing to `appdata` which is a very old location. This file should instead be installed to `metainfo`

**Comment by hezral** [comment]
Same here, fixed.
