### ISSUE TITLE
Change `cmd` key name

### ISSUE THREAD

**Issue by Suzie97** [hezral/keystrokes#2]
# Problem
`cmd` is used in the Apple ecosystem. AFAIK, elementary doesn't use the traditional `cmd`, `super`, `tusk`, `windows` etc. It is just the `looped square` symbol.

# Proposal
I think only using the `looped square` symbol would be consistent with the system.

# Relevant Context
## Blog Post by elementary explaning why they use it
[Why the Looped Square (⌘) Symbol?](https://blog.elementary.io/why-the-looped-square-symbol/)

**Comment by hezral** [comment]
The key names are not manually added. It's provided by the system so if i have to change this manually that would also mean maintaining it if there's any updates. 

I could remove the name itself.

**Comment by Suzie97** [comment]
> The key names are not manually added. It's provided by the system so if i have to change this manually that would also mean maintaining it if there's any updates.
> 
> I could remove the name itself.

Yes, that would work as elementary uses only the symbol and there is no name for the key.
