### ISSUE TITLE
Invalid value for x-appcenter-color-primary-text

### ISSUE THREAD

**Issue by danirabbit** [hezral/keystrokes#4]
https://github.com/hezral/keystrokes/blob/9883267847d145a0f293d05dda3f727138ece642/data/com.github.hezral.keystrokes.appdata.xml.in#L74

Looks like you're missing an `F`

**Comment by hezral** [comment]
fixed with https://github.com/hezral/keystrokes/commit/50796df47c5f4d7aedc25a876289e54875c5e122 🤦🏻‍♂️
