### ISSUE TITLE
Getting errors with the version from elementary OS app center

### ISSUE THREAD

**Issue by thomasaull** [hezral/keystrokes#5]
![image](https://user-images.githubusercontent.com/227756/140722410-e143460c-904e-40ba-bd37-73c2527835af.png)

The app does not start up properly. After launching it from command line:
```bash
flatpak run com.github.hezral.keystrokes
```
i'm getting the following errors:
```bash
Gtk-Message: 11:02:09.018: Failed to load module "canberra-gtk-module"
Keystrokes 1.0.2
** (keystrokes:2): CRITICAL **: 11:02:09.029: Settings.vala:95: Could not connect: No such file or directory
** (keystrokes:2): CRITICAL **: 11:02:09.029: Settings.vala:135: Could not connect: No such file or directory
```
I'd be happy to be of any further assistance to debug this issue

**Comment by hezral** [comment]
thanks for reporting this. i got this issue too but my system wasn't up-to-date. 
Can you run and make sure your system is fully updated and try to run again? Mine was fixed once the system is updated.

**Comment by thomasaull** [comment]
You're right, after updating my system the app starts up normally
