### ISSUE TITLE
strange horizontal line where application title bar is (Debian 11 Xfce)

### ISSUE THREAD

**Issue by SwampRabbit** [hezral/keystrokes#9]
Hello Adi @hezral first, good job on keystrokes, it works pretty well, and I like all the extra settings!

Compiling latest git master from source on Debian 11 and running the Xfce desktop, the application has a strange horizontal line where the application title bar is (where the close button and settings icon come and go).  The application title bar shows up by clicking on it.

It doesn't seem to affect the application at all, but is quite annoying visually, and based on your screenshots here... something isn't right on my end.  **So I'm missing something or it could be a dependency version issue maybe?**
![Screenshot_2021-12-09_08-51-13](https://user-images.githubusercontent.com/59395769/145409306-20d70f10-97bb-43e0-9c30-dc1b60fa4516.png)

```
$ keystrokes
Keystrokes 1.0.2
2021-12-09 08:42:14.649600 active_window_manager started
2021-12-09 08:42:15.151464 key listener started
2021-12-09 08:42:15.403983 mouse listener started
Traceback (most recent call last):
  File "/usr/share/com.github.hezral.keystrokes/keystrokes/window.py", line 310, in on_active_window_changed
    if len(app_data) != 0:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/share/com.github.hezral.keystrokes/keystrokes/window.py", line 310, in on_active_window_changed
    if len(app_data) != 0:
TypeError: object of type 'NoneType' has no len()
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <Resource 0x06618d4a>, sequence_number = 53, major_opcode = 2, minor_opcode = 0
X protocol error:
<class 'Xlib.error.BadWindow'>: code = 3, resource_id = <Resource 0x06400008>, sequence_number = 68, major_opcode = 2, minor_opcode = 0
Traceback (most recent call last):
  File "/usr/share/com.github.hezral.keystrokes/keystrokes/window.py", line 310, in on_active_window_changed
    if len(app_data) != 0:
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/share/com.github.hezral.keystrokes/keystrokes/window.py", line 310, in on_active_window_changed
    if len(app_data) != 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by hezral** [comment]
it looks like its due to the theme style, i made it with flatpak that has the elementary OS theme in it and the css customized based on that. 
you could tweak the application.css for the headerbar as it looks like thats where the line is coming from. 
or you can try building the flatpak. 
You'll need the runtimes first 
```
flatpak remote-add --if-not-exists --system appcenter https://flatpak.elementary.io/repo.flatpakrepo
flatpak install com.github.hezral.clips
```

**Comment by SwampRabbit** [comment]
Ok, thanks for that, I can look at the application.css when I get time.
I checked with several other themes just now (Matcha, Numix, Arc), displays the same.

I'm guessing that right now its only going to show right on the Pantheon DE or if using the flatpak?

The reason I'm trying to get it working properly was to create the Debian package for all Debian based distros (Ubuntu, Mint, MX, etc) no matter the DE/WM they use (Xfce, KDE, Gnome, Cinnamon, Mate).  Not everyone uses or wants flatpaks.

If that's not possible right now, thats ok.

**Comment by hezral** [comment]
thanks, i tested this on ubuntu 21.04, 

add this to the application.css

headerbar#main {
background-image: none;
border-color: transparent;
}

while this fixes the line, a lot of the other styling is still broken though.

**Comment by SwampRabbit** [comment]
@hezral awesome thanks for responding so fast, I can check it out when I get time, have to step away from the computer for the night finally.

I created debian packaging for you.  If you want can you create a empty branch called "deb packaging" and "debian packaging" and I can do a PR for you.  Or I can push it to main/master if that is what you want.

**Comment by hezral** [comment]
i think master should be fine, i have another app that has debian packaging too.

my concern is there might be some breakage due to i'm developing flatpak. Can you test out first?

And how are you handling the python modules installations?

**Comment by SwampRabbit** [comment]
@hezral sorry just getting around to this, for sure will test it before anything else.  
I plan to test it later tonight once I finish other packages.

I'm not sure by what you mean "handling" the python modules installation?
All are available in Debian already, except for pynput, so I already packaged that up first.

When I build the .deb for keystrokes it "should" pull in any python dependencies as expected.
This keystrokes isn't much different than QuickWord, which was easy to do as you do a great job on your applications.

**Comment by hezral** [comment]
Thanks, yeah i meant pynput. Sounds good then.

**Comment by SwampRabbit** [comment]
I have a few packages to work on tonight, but this one is on the list.

I normally use screenkey, but I like what you are doing with keystrokes, I'm sure many others would like to be able to use it too.

**Comment by hezral** [comment]
Thanks appreciate the help! 

There's a few bugs that I'm trying to fix but the latest commit is pretty stable

**Comment by SwampRabbit** [comment]
@hezral really great work!  This issue is resolved now.

I did notice a few minor bugs/oddities at least testing it in a VirtualBox VM.  

I can start another issue thread of those small things I noticed if you want, but you might be working them already?

**Comment by hezral** [comment]
sure, appreciate any issue/feedbacks

thanks!

**Comment by SwampRabbit** [comment]
alright, I'll start a new issue later today at some point, I took notes and output from running it in terminal but I'll verify it again.

the good thing is, the Debian package builds and runs pretty well!
